jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
jwt-password:
  source: ENC(8V7NR+u4LLHB+ApNmHk+zfjdEC6T4242dl6y8G1463KQglM5kRlE4ouSPh4CmwcFLKHrpOLKPMiihrIILLiiBqkVS2zoeUBdiH5g2LaP9b0=)

cool-sms:
  api-key: ENC(EAm2cgIIBNdUQi4aP1V1LDfM3ob4RT2o/1Id8HuPhiA=)
  api-secret: ENC(i5y9kacgHIKrg9LPI20+7+HuEUAR/pW7ED/ectU4sed35UNovJPdpuJrYLWkhEyZ)
  domain : https://api.solapi.com
  phone-number: ENC(Z5LXjSfYsknAko7+LboUUHB/vhNwo2JN) # ????

server:
  tomcat:
    max-part-count: -1
spring:
  config:
    activate:
      on-profile: prod
  server-url:
    base: ENC(jPh8En5VEdBrH+h8kjMkKEc+hfSgapJO/YN5BkLTyHQ=)
    https: ???
  mvc:
    path match:
      matching-strategy: ant_path_matcher #????????? ???? ???? ???
      #    jsp??
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    username: ENC(UelQqkfOLzn2l1MDQtSOYHhUEn3aawyN)
    password: ENC(AYDevY7wFjIsDVu3/Mgdpg==)
    driver-class-name: oracle.jdbc.OracleDriver
    url: ENC(00m7lzqLuEcM4kQQyYT234tgCzC+EvmIQZ9CKYqWYyRZWYC6AVZJtfN5vZ1gibw2)
  jpa:
    open-in-view: false
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(4bljmOjFQJ2PcYIQnT5ObyjxCz/HenQS/lrbm40YbMA=)
    password: ENC(/Fj+o9c4TfOUEJ//Wn2TPC4F/RRUzi/xWriEGAQJtgM=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 20000 # 20?
          starttls:
            enable: true
  #              Identity Manager ??? SSL? ???? SMTP? ????? ?????.
  servlet:
    multipart:
      max-file-size: 10MB #??? 1MB
      max-request-size: 20MB #??? 10MB
  data:
    mongodb:
      database: musicSNS
    redis:
      host: ENC(ChmsegEjtuu13iKH9sSZvaBQEyt9258m)          # EC2 배포 시 localhost 사용하거나 privateIP 사용
      port: 6379
      timeout: 3000
  #Azure Storage
  cloud:
    azure:
      storage:
        blob:
          account-name: ENC(Gfmiwm3gN7aN/QYRS1g/s5g6kI1iBgROApUyCNjNAho=)
          endpoint: ENC(Ww2zX4igndXFi7cnvWjpz9/BexaTrYkqZwBEEi3D79wjVoH/Re6iz0naH2FvqAJAR72k06beCao=)
          container-name: ENC(2HBf78QcGwzb5iXFRAx/cdwpEeLcsQbYPmJHBQySE9A=)
          account-key: ENC(dL/R9JzARBL1YZpG0tQ5A1ojTqWzIaSHlBtCSza7Ivva2lbrkUimdcIhUfUAa21pkpYOPwIiNwCfEZsxs9Ayv0u3eq6mZQk7y+ySPKtq1Jk3DgbwqlMnOvii6ZO6PV8AplVkLLImwec=)


mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.github.musicsnsproject.domain

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /my-docs.html
  version: 1.0.0

file:
  upload:
    directory: /uploads/

portOne:
  primary: ENC(xAqYnBglWkDMrOdy12DMzhBzFpRiKYw2)

spotify:
  client-id: ENC(Mm7ZCyeivezE1UVzqukqVFTiplOmSrw5Mq1MMwCOa0krpUeYVy7+J07WGcRvGzLY)
  client-secret: ENC(gDHITZLMI/poJ0Llc6j5Zsd4ObmNi1u7tkjVQsvwBrmyqChDn8z8UB1vQ12qM9yq)
music:
  chart:
    bugs: https://music.bugs.co.kr/chart
    melon: https://www.melon.com/chart/index.htm
    vibe: https://apis.naver.com/vibeWeb/musicapiweb/vibe/v1/chart/track/total
    genie:
      url1: https://www.genie.co.kr/chart/top200?rtm=Y&pg=1
      url2: https://www.genie.co.kr/chart/top200?rtm=Y&pg=2
oauth:
  microsoft:
    client-id: dummy-client-id
    secret: dummy-secret
    url:
      auth: https://dummy.microsoft.com/auth
      api: https://dummy.microsoft.com/api
  twitter:
    client-id: dummy-client-id
    secret: dummy-secret
    url:
      code: https://dummy.twitter.com/code
      api: https://dummy.twitter.com/api
  facebook:
    client-id: dummy-client-id
    secret: dummy-secret
    url:
      code: https://dummy.facebook.com/code
      api: https://dummy.facebook.com/api
  kakao:
    client-id: dummy-client-id
    secret: dummy-secret
    url:
      auth: https://dummy.kakao.com/auth
      api: https://dummy.kakao.com/api
  naver:
    client-id: dummy-client-id
    secret: dummy-secret
    state: dummy-state
    url:
      auth: https://dummy.naver.com/auth
      api: https://dummy.naver.com/api
  google:
    client-id: dummy-client-id
    secret: dummy-secret
    url:
      code: https://dummy.google.com/code
      auth: https://dummy.google.com/auth
      api: https://dummy.google.com/api
  github:
    client-id: dummy-client-id
    secret: dummy-secret
    url:
      auth: https://dummy.github.com/auth
      api: https://dummy.github.com/api
#oauth:
#  microsoft:
#    client-id: ENC(l8mcLx7QDiYsTwRiPtFlq024tky+nCIgG19OhPPO/K6S5oPmk+mYBG7K/NgyLt05)
#    secret: ENC(G2W8T2wJnGI2YT2QLFbruaePd+TgOQB2POJT51IRAh8e6LfEczaDhDkNrIxCFZRJUTZIym57XEw=)
#    url:
#      auth: https://login.microsoftonline.com
#      api: https://graph.microsoft.com
#  twitter:
#    client-id: ENC(nFWZ+e0FzaGqbSXuHlQBAqRyT7NQ7XrDbKDHqtc26VwNIbkqRUBZf6lKIm4QxTqQ)
#    secret: ENC(yTOGJlRzEBIFgL0kxjY1+52p71TpqWrWpQxHvxQWLkg5e/vfoctF/7DIWnNvKHr5n0LsFL0/ulFl9ZKRnQO5Ow==)
#    url:
#      code: https://x.com
#      api: https://api.x.com
#  facebook:
#    client-id: ENC(qzUop3NaBKIS7iDr7GOB8/uMY27k+iE6wgItyJrNvNE=)
#    secret: ENC(6IpKXK0B2FAakWgMoMJjYRjqyqs23Bl2q4awbmk2koqJAzrd0B+AmzjapRUqa3w1)
#    url:
#      code: https://www.facebook.com
#      api: https://graph.facebook.com
#  kakao:
#    client-id: ENC(gjUFMFT1Kyqa9rpUO3mNOr/vR2wxzLcrIIVyVS5QYOad3nOotSmNXW0zypxNa50V)
#    secret: ENC(OiSWBApzK8Q2GOJygo2uKhan+KMYr2HrG9KG8kl4ZQP8CTUKP6jwd4E+6oXtKYLZ)
#    url:
#      auth: https://kauth.kakao.com
#      api: https://kapi.kakao.com
#  naver:
#    client-id: ENC(nH/XcmbwN4/PHHItYW2XtvBYU1EjqIZE+SdEOj8yi98=)
#    secret: ENC(wS40SiGJ4bPNGYfgcfPjHZMfje8HsK3l)
#    state: ENC(h9I5trQ5Jl/2wSgkE+yVAKUsy1evsno84t8lwzExAS4=)
#    url:
#      auth: https://nid.naver.com
#      api: https://openapi.naver.com
#  google:
#    client-id: ENC(t36nBH1/CPZ4i23e7T+mtn4dPREHfmox6Kyzmje0VdJfj0IQ/iQoeBIg+pFeypilWG6xuYZsknp7tdUMjF7XdwL+pp/MtfMfzB4j5Ya290I0J2fef/gOaw==)
#    secret: ENC(ArmCJ+zXlxmZ2wNyHDROb6dzwbXwFlV6TCeFKlD9HLnYncvicuczNdTergX8yhKM)
#    url:
#      code: https://accounts.google.com
#      auth: https://oauth2.googleapis.com
#      api: https://www.googleapis.com
#  github:
#    client-id: ENC(KbMoBUJk5DvVKa8bGowKowCkrP4xL9l5Hy/F8vx3Ek0=)
#    secret: ENC(m2akYCPA/+wAOD4403hpYAuxHxRNuprW2HPL8YWTJfP/djnCyF75O4mysJaATcXjCj+bE77ekyQ=)
#    url:
#      auth: https://github.com
#      api: https://api.github.com

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.cluster: INFO
    org.mongodb.driver.protocol.command: DEBUG